services:
  nginx:
    image: nginx

ingress:
  service: nginx
  port: 80

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
