services:
  example-worker:
    build:
      context: https://github.com/UffizziCloud/example-voting-worker
      dockerfile: Dockerfile
  example-vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote
      dockerfile: Dockerfile
  example-result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result
      dockerfile: Dockerfile

ingress:
  service: example-vote
  port: 80

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
